# This is a basic workflow to help you get started with Actions

name: Build dev branch for test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  publish:
    name: Checkout & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - run: yarn release
        env:
          CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}

      - name: Upload dev_build_zip
        uses: actions/upload-artifact@v2
        with:
          name: dev-build-${{ steps.short-sha.outputs.sha }}-zip
          path: releases/*.zip

      - name: Upload dev_build_crx
        uses: actions/upload-artifact@v2
        with:
          name: dev-build-${{ steps.short-sha.outputs.sha }}-crx
          path: releases/*.crx
